(function(){
var AK='5CG0k5JOyBmd//v8xqTDzKbJlSwXImB6y91SErZWfd0=';
var AB='/pdev/'+atob('YXBp');
var SF=atob('c2Vzc2lvbnM=');
function toast(m,e){var t=document.createElement('div');t.textContent=m;t.style.cssText='position:fixed;bottom:20px;right:20px;padding:12px 24px;border-radius:6px;z-index:9999;color:white;background:'+(e?'#ef4444':'#22c55e');document.body.appendChild(t);setTimeout(function(){t.remove()},3000);}
window.endItem=function(id){if(!confirm('End?'))return;var x=new XMLHttpRequest();x.open('POST',AB+'/'+SF+'/'+id+'/complete');x.setRequestHeader('Content-Type','application/json');x.onerror=function(){toast('Network error',1);};x.onload=function(){if(x.status<300){toast('Ended');loadItems();}else{toast('Failed: '+x.status,1);}};x.send('{"status":"completed"}');};
window.delItem=function(id){if(!confirm('Delete?'))return;var x=new XMLHttpRequest();x.open('DELETE',AB+'/'+SF+'/'+id);x.setRequestHeader('X-Admin-Key',AK);x.onerror=function(){toast('Network error',1);};x.onload=function(){if(x.status<300){toast('Deleted');loadItems();}else{toast('Failed: '+x.status,1);}};x.send();};
window.clearAll=function(){if(!confirm('Delete ALL?'))return;if(!confirm('Really?'))return;var x=new XMLHttpRequest();x.open('DELETE',AB+'/'+SF);x.setRequestHeader('X-Admin-Key',AK);x.onerror=function(){toast('Network error',1);};x.onload=function(){if(x.status<300){toast('Cleared');loadItems();}else{toast('Failed: '+x.status,1);}};x.send();};
window.loadItems=function(){var x=new XMLHttpRequest();x.open('GET',AB+'/'+SF+'/active');x.onerror=function(){toast('Network error',1);};x.onload=function(){if(x.status<300)renderCards(JSON.parse(x.responseText));};x.send();};
function renderCards(items){var g=document.getElementById('cardGrid');if(!g)return;if(!items||!items.length){g.innerHTML='<div class="empty-state"><div class="icon">📭</div><p>No items</p></div>';return;}
g.innerHTML=items.map(function(i){return '<div class="scard" onclick="location.href=\'session.html?id='+i.id+'\'"><div class="shead"><span class="sproj">'+((i.project_name||'?'))+'</span><span class="scmd">/'+((i.command_type||'?'))+'</span></div><div class="smeta">'+((i.server_origin||''))+' - '+((i.total_steps||0))+' steps</div><div class="sbtns"><button onclick="event.stopPropagation();endItem(\''+i.id+'\')" class="sbtn sw">End</button><button onclick="event.stopPropagation();delItem(\''+i.id+'\')" class="sbtn sd">Del</button></div></div>';}).join('');}
var cs=document.createElement('style');cs.textContent='.scard{background:var(--card);border:1px solid var(--border);border-radius:8px;padding:1rem;cursor:pointer;}.scard:hover{border-color:var(--accent);}.shead{display:flex;justify-content:space-between;margin-bottom:.5rem}.sproj{font-weight:600}.scmd{color:var(--accent);font-family:monospace}.smeta{color:var(--muted);font-size:.85rem;margin-bottom:.75rem}.sbtns{display:flex;gap:.5rem}.sbtn{padding:.25rem .5rem;font-size:.75rem;border:none;border-radius:4px;cursor:pointer}.sw{background:var(--warn);color:#000}.sd{background:#ef4444;color:#fff}.clrBtn{background:#dc2626;color:white;padding:.5rem 1rem;border:none;border-radius:4px;cursor:pointer;margin-left:auto}#cardGrid{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:1rem;padding:1rem}';document.head.appendChild(cs);
document.addEventListener('DOMContentLoaded',function(){
var h=document.querySelector('header');if(h){var b=document.createElement('button');b.className='clrBtn';b.textContent='Clear All';b.onclick=clearAll;h.appendChild(b);}
var op=document.querySelector('.output-panel');if(op){op.innerHTML='<div class="output-header"><span>Active Items</span><button class="btn btn-outline" onclick="loadItems()">Refresh</button></div><div id="cardGrid"></div>';}
loadItems();setInterval(loadItems,30000);
});
})();
